### ISSUE TITLE
Issue with timeouts

### ISSUE THREAD

**Issue by Tineyko** [XternA/cryptos-faucets-bot#1]
There is a timeout issue for coinfaucet.io, bot is unable to find email input field.

Timeout also occurs at second run when bot is  trying to apply promo codes

**Comment by XternA** [comment]
The issue caused for coinfaucet.io (Ripple XRP) was due to the fact that the Chainlink URL has changed since but the link is still valid and will direct us to the XRP page that I've noticed. Hence when it reached to XRP the page is already logged in. This has been updated now.

Regarding timeout issues this is due to Puppeteer sometimes unable to navigate to the page in time and can get quite flaky. Nothing much I can do as of now but things seems to be working for me as I've updated the code base. Kindly pull the new changes.

**Comment by Tineyko** [comment]
Everything works smoothly now, great job, thanks :)
